-- Strategist Reports Table
-- Purpose: Store the daily/periodic synthesis reports generated by the Backend AI Manager
CREATE TABLE IF NOT EXISTS strategist_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_type TEXT DEFAULT 'daily_digest', -- daily_digest, lead_audit, anomaly_alert
    content JSONB NOT NULL, -- The structured findings (Top Keywords, Leads to watch, Anomaly count)
    summary TEXT, -- Human readable summary
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Extend saas_leads with priority
ALTER TABLE saas_leads ADD COLUMN IF NOT EXISTS priority_score INTEGER DEFAULT 0; -- 1-5 Scale
ALTER TABLE saas_leads ADD COLUMN IF NOT EXISTS lead_category TEXT DEFAULT 'Cold'; -- Hot, Warm, Cold
